insert into film(title, description, release_year, length) values('Legends Of The Fall', 'A melodrama with Brad Pitt and Anthony hopkins', 1995, 133);
insert into film(title, description, release_year, length) values('The Matrix', 'Film with digital green on black', 2000, 165);
insert into film(title, description, release_year, length) values('Lawrence Of Arabia', 'Desert dwellers attack ottoman empire', 1987, 142);
insert into film(title, description, release_year, length) values('Reservoir Dogs', 'Criminals perform a bank robbery', 2003, 95);
insert into film(title, description, release_year, length) values('Once Upon A Time In The West', 'Spaghetti western', 1998, 120);
insert into actor(name, nationality, year_of_birth, description) values('Joe', 'American', 1950, 'Average Guy');
insert into actor(name, nationality, year_of_birth, description) values('Matthias Schoenaerts', 'Belgian', 1977, "Belgian Quality");
insert into actor(name, nationality, year_of_birth, description) values('Bradd Spitt', 'Amerikaan', 1980, "Melkmuil");
insert into actor(name, nationality, year_of_birth, description) values('Anne Hathaway', 'American', 1970, "Brown-haired beauty");
insert into actor(name, nationality, year_of_birth, description) values('Nicole Kidman', 'Australian', 1967, "Roodharige Vamp");
