insert into film(title, description, release_year, length) values('Legends Of The Fall', 'A melodrama with Brad Pitt and Anthony hopkins', 1995, 133);
insert into film(title, description, release_year, length) values('The Matrix', 'Film with digital green on black', 2000, 165);
insert into film(title, description, release_year, length) values('Lawrence Of Arabia', 'Desert dwellers attack ottoman empire', 1987, 142);
insert into film(title, description, release_year, length) values('Reservoir Dogs', 'Criminals perform a bank robbery', 2003, 95);
insert into film(title, description, release_year, length) values('Once Upon A Time In The West', 'Spaghetti western', 1998, 120);
insert into actor(name, nationality, year_of_birth, description) values('Joe SixPack', 'American', 1950, 'The Average Guy');
insert into actor(name, nationality, year_of_birth, description) values('Matthias Schoenaerts', 'Belgian', 1977, "Belgisch ras- en boerenpaard");
insert into actor(name, nationality, year_of_birth, description) values('Bradd Spitt', 'Amerikaan', 1980, "Eeuwige melkmuil");
insert into actor(name, nationality, year_of_birth, description) values('Anne Hathaway', 'American', 1970, "Bruinharige beauty");
insert into actor(name, nationality, year_of_birth, description) values('Nicole Kidman', 'Australian', 1967, "Roodharige vamp from down under");
insert into review(review_text, rating, film_id) values('Romantisch en dramatisch !', '9', '1');
insert into review(review_text, rating, film_id) values('Flauwe Tearjerker !', '3', '1');
insert into review(review_text, rating, film_id) values('OK, maar wel Langdradig', '6', '1');
